In [1]:
import numpy as np

In [18]:
points = {'1': (0.5, 0.5),
          '2': (0.7, 0.7),
          '3': (0.6, 0.6)}

In [19]:
test = points.values()

In [20]:
xy = tuple(zip(*test))

In [23]:
susi = np.polynomial.legendre.legvander2d(*xy, (2, 2))

In [25]:
tuple(susi)

(array([ 1.      ,  0.5     , -0.125   ,  0.5     ,  0.25    , -0.0625  ,
        -0.125   , -0.0625  ,  0.015625]),
 array([ 1.      ,  0.7     ,  0.235   ,  0.7     ,  0.49    ,  0.1645  ,
         0.235   ,  0.1645  ,  0.055225]),
 array([ 1.    ,  0.6   ,  0.04  ,  0.6   ,  0.36  ,  0.024 ,  0.04  ,
         0.024 ,  0.0016]))

In [26]:
tuple(np.array([1, 2]))

(1, 2)

In [27]:
ValuesView

NameError: name 'ValuesView' is not defined

In [99]:
from multiprocessing import Pipe

In [112]:
pipe_out, pipe_in = Pipe(duplex=False)

In [125]:
for i in range(4000):
    pipe_in.send('hello')

KeyboardInterrupt: 

In [123]:
n = 0
while pipe_out.poll():
    pipe_out.recv()
    n += 1

In [124]:
n

3000

In [98]:
pipe_in.writable

True

In [80]:
pipe_out.poll(timeout=1.)

True

In [70]:
if pipe_out.poll(timeout=1.):
    try:
        pipe_out.recv()
    except EOFError:
        print('hello')

hello


In [95]:
pipe_out.recv()

EOFError: 

In [148]:
from time import monotonic, perf_counter, clock_getres, get_clock_info, CLOCK_MONOTONIC

In [149]:
clock_getres(CLOCK_MONOTONIC)

1e-09

In [147]:
get_clock_info('monotonic')

namespace(adjustable=False, implementation='clock_gettime(CLOCK_MONOTONIC)', monotonic=True, resolution=1e-09)